#!/bin/bash

# color variables
RED='\e[31m'
GREEN='\e[32m'
YELLOW='\e[33m'
BLUE='\e[34m'
RESET='\e[0m'

echo " "
echo " ___ ___  ____"
echo "|_ _/ _ \|  _ \\"
echo " | | | | | | | |"
echo " | | |_| | |_| |"
echo "|___\__\_\____/ Install Qemu Debian by Liamsi"
echo " "
echo "-----------------------------------------------"

# Check if the virtualization is enabled on this computer
virten=$(egrep -c '(vmx|svm)' /proc/cpuinfo)

echo -e "${BLUE}> Checking if virtualization is enabled...${RESET}"

if [[ $virten -gt 0 ]]; then
  echo -e "\n${GREEN}Virtualization is enabled${RESET}"
else 
  echo -e "\n${RED}Virtualization isn't enabled${RESET}"
  echo -e "Go to bios settings and enable VT-x (Virtualization Technology Extension) for Intel processor and AMD-V for AMD processor."
  exit 1
fi

# Installing requirement

echo -e "\n${BLUE}> Installing requirement...${RESET}"

sudo apt install nala

sudo nala install qemu-kvm qemu-system qemu-utils python3 python3-pip libvirt-clients libvirt-daemon-system bridge-utils virtinst libvirt-daemon virt-manager -y

# Starting libvirtd daemon

echo -e "\n${BLUE}> Starting libvirtd...${RESET}"

sudo systemctl enable libvirtd
sudo systemctl start libvirtd

# Start Default Network for Networking

echo -e "\n${BLUE}> Start Default Network for Networking...${RESET}"

sudo virsh net-start default
sudo virsh net-autostart default

echo -e "\n${BLUE}> Cheking network status: ${RESET}"

sudo virsh net-list --all

# Add User to libvirt to Allow Access to VMs
echo -e "\n${BLUE}> Add User to libvirt to Allow Access to VMs...${RESET}"

sudo usermod -aG libvirt $USER
sudo usermod -aG libvirt-qemu $USER
sudo usermod -aG kvm $USER
sudo usermod -aG input $USER
sudo usermod -aG disk $USER

# End
echo -e "-------------------------------------"
echo -e "\n${GREEN}> Reboot and you are Finished!${RESET}"
